# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import attestation_pb2 as attestation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in attestation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AttestationServiceStub(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    AttestationService runs on each drone. Peers push their SignedReceipt
    objects to it; the service replies with the peer's SignedVote.

    One-receipt-one-vote semantics: calling SubmitReceipt twice for the
    same receipt is idempotent — the same SignedVote is returned. The
    caller may also stream votes to peers as they accumulate, separately
    from this synchronous RPC, to handle network drops.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitReceipt = channel.unary_unary(
                '/veriswarm.v1.AttestationService/SubmitReceipt',
                request_serializer=attestation__pb2.SignedReceipt.SerializeToString,
                response_deserializer=attestation__pb2.SignedVote.FromString,
                _registered_method=True)
        self.PushVote = channel.unary_unary(
                '/veriswarm.v1.AttestationService/PushVote',
                request_serializer=attestation__pb2.SignedVote.SerializeToString,
                response_deserializer=attestation__pb2.PushVoteAck.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/veriswarm.v1.AttestationService/Ping',
                request_serializer=attestation__pb2.PingRequest.SerializeToString,
                response_deserializer=attestation__pb2.PingResponse.FromString,
                _registered_method=True)


class AttestationServiceServicer(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    AttestationService runs on each drone. Peers push their SignedReceipt
    objects to it; the service replies with the peer's SignedVote.

    One-receipt-one-vote semantics: calling SubmitReceipt twice for the
    same receipt is idempotent — the same SignedVote is returned. The
    caller may also stream votes to peers as they accumulate, separately
    from this synchronous RPC, to handle network drops.

    """

    def SubmitReceipt(self, request, context):
        """Synchronous: peer submits a SignedReceipt and gets this drone's
        signed vote on it back. Used in the steady-state protocol.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushVote(self, request, context):
        """Asynchronous push: a peer broadcasts a SignedVote it produced for
        some receipt (so the receiving drone can fold it into its own
        tally). The reply is a simple ACK message — see PushVoteAck.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health probe used by the supervisor / sim launcher.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttestationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitReceipt,
                    request_deserializer=attestation__pb2.SignedReceipt.FromString,
                    response_serializer=attestation__pb2.SignedVote.SerializeToString,
            ),
            'PushVote': grpc.unary_unary_rpc_method_handler(
                    servicer.PushVote,
                    request_deserializer=attestation__pb2.SignedVote.FromString,
                    response_serializer=attestation__pb2.PushVoteAck.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=attestation__pb2.PingRequest.FromString,
                    response_serializer=attestation__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'veriswarm.v1.AttestationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('veriswarm.v1.AttestationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttestationService(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    AttestationService runs on each drone. Peers push their SignedReceipt
    objects to it; the service replies with the peer's SignedVote.

    One-receipt-one-vote semantics: calling SubmitReceipt twice for the
    same receipt is idempotent — the same SignedVote is returned. The
    caller may also stream votes to peers as they accumulate, separately
    from this synchronous RPC, to handle network drops.

    """

    @staticmethod
    def SubmitReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veriswarm.v1.AttestationService/SubmitReceipt',
            attestation__pb2.SignedReceipt.SerializeToString,
            attestation__pb2.SignedVote.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veriswarm.v1.AttestationService/PushVote',
            attestation__pb2.SignedVote.SerializeToString,
            attestation__pb2.PushVoteAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veriswarm.v1.AttestationService/Ping',
            attestation__pb2.PingRequest.SerializeToString,
            attestation__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
