# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: attestation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'attestation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ttestation.proto\x12\x0cveriswarm.v1\"x\n\x07Receipt\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x03\x12\x12\n\ninput_hash\x18\x03 \x01(\t\x12\x12\n\nmodel_hash\x18\x04 \x01(\t\x12\x0e\n\x06output\x18\x05 \x03(\x01\x12\r\n\x05nonce\x18\x06 \x01(\t\"N\n\rSignedReceipt\x12&\n\x07receipt\x18\x01 \x01(\x0b\x32\x15.veriswarm.v1.Receipt\x12\x15\n\rsignature_hex\x18\x02 \x01(\t\"\x85\x01\n\x08PeerVote\x12\x10\n\x08voter_id\x18\x01 \x01(\t\x12\x1b\n\x13target_receipt_hash\x18\x02 \x01(\t\x12$\n\x08\x64\x65\x63ision\x18\x03 \x01(\x0e\x32\x12.veriswarm.v1.Vote\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x05 \x01(\x03\"I\n\nSignedVote\x12$\n\x04vote\x18\x01 \x01(\x0b\x32\x16.veriswarm.v1.PeerVote\x12\x15\n\rsignature_hex\x18\x02 \x01(\t\"/\n\x0bPushVoteAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"$\n\x0bPingRequest\x12\x15\n\rfrom_drone_id\x18\x01 \x01(\t\";\n\x0cPingResponse\x12\x15\n\rthis_drone_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x03*2\n\x04Vote\x12\x14\n\x10VOTE_UNSPECIFIED\x10\x00\x12\x07\n\x03\x41\x43K\x10\x01\x12\x0b\n\x07\x44ISPUTE\x10\x02\x32\xdc\x01\n\x12\x41ttestationService\x12\x46\n\rSubmitReceipt\x12\x1b.veriswarm.v1.SignedReceipt\x1a\x18.veriswarm.v1.SignedVote\x12?\n\x08PushVote\x12\x18.veriswarm.v1.SignedVote\x1a\x19.veriswarm.v1.PushVoteAck\x12=\n\x04Ping\x12\x19.veriswarm.v1.PingRequest\x1a\x1a.veriswarm.v1.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attestation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTE']._serialized_start=596
  _globals['_VOTE']._serialized_end=646
  _globals['_RECEIPT']._serialized_start=35
  _globals['_RECEIPT']._serialized_end=155
  _globals['_SIGNEDRECEIPT']._serialized_start=157
  _globals['_SIGNEDRECEIPT']._serialized_end=235
  _globals['_PEERVOTE']._serialized_start=238
  _globals['_PEERVOTE']._serialized_end=371
  _globals['_SIGNEDVOTE']._serialized_start=373
  _globals['_SIGNEDVOTE']._serialized_end=446
  _globals['_PUSHVOTEACK']._serialized_start=448
  _globals['_PUSHVOTEACK']._serialized_end=495
  _globals['_PINGREQUEST']._serialized_start=497
  _globals['_PINGREQUEST']._serialized_end=533
  _globals['_PINGRESPONSE']._serialized_start=535
  _globals['_PINGRESPONSE']._serialized_end=594
  _globals['_ATTESTATIONSERVICE']._serialized_start=649
  _globals['_ATTESTATIONSERVICE']._serialized_end=869
# @@protoc_insertion_point(module_scope)
