"""Deterministic training support for the Samik rescue person detector.

This package contains contracts and data-preparation utilities only.  Importing
it never downloads data, initializes CUDA, or starts training.
"""

from .artifact_io import (
    ArtifactIOError,
    atomic_create_json,
    canonical_json_bytes,
    create_external_json,
    require_external_workspace,
    require_path_within_workspace,
    sha256_file,
)
from .contracts import (
    FROZEN_GATES,
    FROZEN_RUNTIME,
    MODEL_ID,
    PERSON_CLASS_MAP,
    RUNPOD_WORKSPACE_ROOT,
    TRAINING_PLAN_SCHEMA,
    CandidateSpec,
    TrainingContractError,
    TrainingPlan,
)
from .dataset_intake import (
    DATASET_ARCHIVE_REGISTRATION_SCHEMA,
    DATASET_EXTRACTION_INVENTORY_SCHEMA,
    DATASET_EXTRACTION_MANIFEST_SCHEMA,
    DATASET_RESPONSE_METADATA_SCHEMA,
    FROZEN_DATASET_IDENTITIES,
    ArchiveRegistrationResult,
    DatasetIntakeError,
    ExtractionResult,
    FrozenDatasetIdentity,
    ValidatedExtractionEvidence,
    extract_registered_zip,
    register_dataset_archive,
    validate_dataset_extraction_manifest,
)
from .visdrone import (
    OFFICIAL_SPLIT_COUNTS,
    OFFICIAL_SPLIT_DATASET_KEYS,
    PERSON_SOURCE_CATEGORIES,
    VISDRONE_LINEAGE_VALIDATION_SCHEMA,
    VISDRONE_REPORT_SCHEMA,
    SplitConversionReport,
    VisDroneConversionError,
    VisDroneConversionReport,
    convert_visdrone_det,
    read_image_dimensions,
    validate_visdrone_conversion_report,
)

__all__ = [
    "ArtifactIOError",
    "CandidateSpec",
    "DATASET_ARCHIVE_REGISTRATION_SCHEMA",
    "DATASET_EXTRACTION_INVENTORY_SCHEMA",
    "DATASET_EXTRACTION_MANIFEST_SCHEMA",
    "DATASET_RESPONSE_METADATA_SCHEMA",
    "DatasetIntakeError",
    "ExtractionResult",
    "FROZEN_GATES",
    "FROZEN_DATASET_IDENTITIES",
    "FROZEN_RUNTIME",
    "FrozenDatasetIdentity",
    "ValidatedExtractionEvidence",
    "MODEL_ID",
    "OFFICIAL_SPLIT_COUNTS",
    "OFFICIAL_SPLIT_DATASET_KEYS",
    "PERSON_CLASS_MAP",
    "PERSON_SOURCE_CATEGORIES",
    "RUNPOD_WORKSPACE_ROOT",
    "TRAINING_PLAN_SCHEMA",
    "TrainingContractError",
    "TrainingPlan",
    "VISDRONE_REPORT_SCHEMA",
    "VISDRONE_LINEAGE_VALIDATION_SCHEMA",
    "SplitConversionReport",
    "VisDroneConversionError",
    "VisDroneConversionReport",
    "ArchiveRegistrationResult",
    "atomic_create_json",
    "canonical_json_bytes",
    "create_external_json",
    "convert_visdrone_det",
    "extract_registered_zip",
    "read_image_dimensions",
    "validate_dataset_extraction_manifest",
    "validate_visdrone_conversion_report",
    "require_external_workspace",
    "require_path_within_workspace",
    "register_dataset_archive",
    "sha256_file",
]
